version: "3.9"

networks:
  monitor-net:

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    restart: unless-stopped
    networks:
      - monitor-net
    ports:
      - "8080:8080"   # Expose cAdvisor on the host
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - --docker_only=true
      - --housekeeping_interval=10s

  dockerstats:
    build: .
    container_name: docker-stats-test
    restart: unless-stopped
    depends_on:
      - cadvisor
    networks:
      - monitor-net
    ports:
      - "5001:5000"   # Expose the monitor app on the host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./users.db:/app/users.db
    environment:
      #AUTH_USER: "admin"
      #AUTH_PASSWORD: "admin"
      LOGIN_MODE: "page"  # New: Login mode - 'popup' (default) or 'page'
      CADVISOR_URL: "http://cadvisor:8080"
      PUSHOVER_TOKEN: ${PUSHOVER_TOKEN}
      PUSHOVER_USER: ${PUSHOVER_USER}
      NVIDIA_VISIBLE_DEVICES: all
      GPU_METRICS_ENABLED: "true"
    # For hosts with an NVIDIA GPU and the NVIDIA Container Toolkit, you can uncomment the deploy/resources/devices section.
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]

# Secrets (optional)
# secrets:
#   auth_password:
#     file: ./auth_password.txt
