version: "3.9"
services:
  monitor:
    build: .
    container_name: docker-stats-test
    ports:
      - "5001:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      AUTH_USER: "admin"
      AUTH_PASSWORD: "admin"
      # Uncomment the line below to use a Docker secret for the password
      # AUTH_PASSWORD_FILE: /run/secrets/auth_password
    # Uncomment the lines below to define and use the Docker secret
    # secrets:
    #   - auth_password

# Uncomment the lines below to define the Docker secret
# secrets:
#   auth_password:
#     file: ./auth_password.txt # Path to the file containing the password on the host
